name: "Validate Bundle"

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  validate-bundle:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
      DATABRICKS_BUNDLE_ENV: dev

    steps:
    - uses: actions/checkout@v4
    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.9.16"
        python-version: ${{ matrix.python-version }}
        enable-cache: true
    - uses: databricks/setup-cli@main
      with:
        version: 0.280.0
    - name: Install the project
      run: uv sync --locked --all-extras
    - name: Check Databricks CLI
      run: databricks current-user me
    - name: Validate Databricks Bundle
      run: databricks bundle validate